name: Build Android Kernel

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential ccache curl flex git gnupg gperf libncurses5-dev \
          libssl-dev libxml2-utils lzop openjdk-11-jdk python3 python3-pip \
          unzip zip zlib1g-dev
       

    # --- SSH Debug Step ---
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false # Recommended: only you can access the session
    # -----------------------
          
